---
- name: Onboard Kubernetes control plane nodes
  hosts: kube_control_plane
  become: true
  roles:
    - k8s_control_plane

- name: Onboard Kubernetes worker nodes
  hosts: kube_worker
  become: true
  roles:
    - k8s_worker_node

- name: Install Kubernetes network plugin (Cilium)
  hosts: kube_control_plane
  become: true
  roles:
    - k8s_network
